cake-contrib/Cake.Http

- docs/input/docs/usage/examples.md
> Fix typo in example

- nuspec/nuget/Cake.Http.nuspec
- src/Cake.Http/Cake.Http.csproj
- src/Cake.Http/FodyWeavers.xml
- src/Cake.Http/packages.config
> Added Costura.Fody to build the plugin

- src/Cake.Http.Tests/Cake.Http.Tests.csproj
- src/Cake.Http.Tests/packages.config
- src/Cake.Http/Cake.Http.csproj
- src/Cake.Http/packages.config
Lower json.net requirement for issue #13
> Lower Json.Net Requirement

- src/Cake.Http.Tests/Unit/HttpSettingsExtensionsTests.cs
- src/Cake.Http/HttpSettingsExtensions.cs
Changes to add a new extension method for EnsureStatusCode
> EnsureStatusCode Extension Method Changes #18

- nuspec/nuget/Cake.Http.nuspec
> Update nuspec with new cake-contrib icon

- src/Cake.Http/CakeHttpClientHandler.cs
- src/Cake.Http/HttpSettings.cs
- src/Cake.Http/HttpSettingsExtensions.cs
> Added EnsureResponseStatus with optional throw option

- src/Cake.Http/HttpClientAliases.cs
> Add namespace import for System.Net.Http

- nuspec/nuget/Cake.Http.nuspec
This addes the nuspec dependencies for issue #31
> Nuspec Dependencies Added

- nuspec/nuget/Cake.Http.nuspec
- src/Cake.Http/Cake.Http.csproj
> Add dlls to nuget package

- nuspec/nuget/Cake.Http.nuspec
- src/Cake.Http.Tests/Unit/HttpClientAliasesTests.cs
- src/Cake.Http/Cake.Http.csproj
- src/Cake.Http/HttpClientAliases.cs
Remove Hard Reference to HttpRequestMessage in favor of parameters
> Remove direct references to System.Net.Http

- nuspec/nuget/Cake.Http.nuspec
- src/Cake.Http.Tests/Cake.Http.Tests.csproj
- src/Cake.Http/Cake.Http.csproj
> Update Cake Version to 0.22.0 and Target 46 .Net Framework

- setup.cake
> Relax Code inspector

- tools/packages.config
Update latest version of pinned version of cake
> Update latest version of pinned version of cake

- setup.cake
- tools/packages.config
> Relax codeCov build

- nuspec/nuget/Cake.Http.nuspec
- src/Cake.Http.Tests/Cake.Http.Tests.csproj
- src/Cake.Http.Tests/Fixtures/CakeContextFixture.cs
- src/Cake.Http/Cake.Http.csproj
This PR fixes #47 . Hope it's usefull, please let me know if I should change anything!
> Updated cake.core to 0.26.1 and target framework to netstandard2.0

- nuspec/nuget/Cake.Http.nuspec
- src/Cake.Http.Tests/Cake.Http.Tests.csproj
- src/Cake.Http.Tests/Fixtures/CakeContextFixture.cs
- src/Cake.Http.Tests/Unit/HttpSettingsExtensionsTests.cs
- src/Cake.Http/Cake.Http.csproj
- tools/packages.config
> Bump dependencies

- src/Cake.Http.Tests/Cake.Http.Tests.csproj
- src/Cake.Http/Cake.Http.csproj
Remove System.Net.Http Reference. It is already added by .NET Standard library.
It resolved issue #56.
> Remove System.Net.Http Reference

- src/Cake.Http.Tests/Unit/CakeHttpClientHandlerTests.cs
- src/Cake.Http.Tests/Unit/HttpClientAliasesTests.cs
- src/Cake.Http.Tests/Unit/HttpSettingsExtensionsTests.cs
- src/Cake.Http/HttpSettingsExtensions.cs
- src/Cake.Http/JsonEncoder.cs
Added ExtensionMethod to allow naming MultiForm File Uploads
> Added ExtensionMethod to allow naming MultiForm File Uploads

- src/Cake.Http/HttpSettingsExtensions.cs
SetMultipartFormDataRequestBody: logic error fix
> SetMultipartFormDataRequestBody: logic error fix

- nuspec/nuget/Cake.Http.nuspec
> Adds cake-addin tag to NuGet package

- LICENSE
- nuspec/nuget/Cake.Http.nuspec
- src/Cake.Http.Tests/Cake.Http.Tests.csproj
- src/Cake.Http/Cake.Http.csproj
- src/Cake.Http/CakeHttpClientHandler.cs
- src/Cake.Http/HttpClientAliases.cs
- src/Cake.Http/HttpClientAsyncAliases.cs
- src/Cake.Http/HttpSettings.cs
- src/Cake.Http/HttpSettingsExtensions.cs
> Update to Cake 3.0

- src/Cake.Http/JsonEncoder.cs
> 80 JsonEncoder allow Datacontract
